from enum import IntEnum


class BusyStatus(IntEnum):
    "system is not busy"
    BUSY_STATUS_NOT = 0
    "system is switching instrument mode"
    BUSY_STATUS_MS_INSTRUMENT_MODE = 1
    "system is switching acquisition state"
    BUSY_STATUS_TT_STATE = 2
    "system state is NOT READY"
    BUSY_STATUS_MS_NOT_READY = 4


class AcquisitionStatus(IntEnum):
    "current acquisition status ( NOT ACTIVE )"
    ACQUISITION_STATUS_NOT_ACTIVE = 0
    "current acquisition status ( ACTIVE )"
    ACQUISITION_STATUS_ACTIVE = 1
    "current acquisition status ( PAUSED )"
    ACQUISITION_STATUS_PAUSED = 2


class InstrumentMode(IntEnum):
    "undefined current mode"
    INSTR_MODE_UNDEFINED = -1
    "current mode SHUTDOWN"
    INSTR_MODE_SHUTDOWN = 0
    "current mode STANDBY"
    INSTR_MODE_STANDBY = 1
    "current mode STANDBY INSTRUMENT"
    INSTR_MODE_STANDBY_INSTR = 2
    "current mode OPERATE ( system state is READY )"
    INSTR_MODE_OPERATE = 3
    "current mode OPERATE ( system state is NOT READY )"
    INSTR_MODE_OPERATE_NOT_READY = 4


class BrukerMSError(Exception):
    def __repr__(self) -> str:
        err_code, *_ = self.args
        return f"{self.__class__.__name__}({err_code.name})"


class GeneralError(IntEnum):
    ID_ERROR_NO_ERROR = 0

    ID_ERROR_NULL_POINTER = 10
    ID_ERROR_EXCEPTION = 11
    ID_ERROR_EXCEPTION_STANDARD = 12
    ID_ERROR_EXCEPTION_MFC = 13
    ID_ERROR_EXCEPTION_OLE = 14
    ID_ERROR_EXCEPTION_BFL = 15
    ID_ERROR_EXCEPTION_AIDA = 16
    ID_ERROR_EXCEPTION_NTB = 17
    ID_ERROR_XML_FILE_EXCEPTION = 18

    ID_ERROR_NO_COM_INTERFACE = 30
    ID_ERROR_AUTOMATION_CALL = 31
    ID_ERROR_LIB_SUB_METHOD_MANAGMENT = 32
    ID_ERROR_CANT_CREATE_SHAREDMEM = 33
    ID_ERROR_COMPONENT_NO_INTERFACE = 34

    ID_ERROR_ACQ_CANT_START_MISSING_SAMPLE_INFO = 38
    ID_ERROR_ACQ_CANT_START_CHANGE_SOURCE = 39
    ID_ERROR_ACQ_CANT_START_MS_NOT_READY = 40
    ID_ERROR_ACQ_CANT_START_WRONG_MODE = 41
    ID_ERROR_ACQ_IS_ACTIVE = 42
    ID_ERROR_ACQ_IS_NOT_ACTIVE = 43
    ID_ERROR_ACQ_CANT_START_CI_SOURCE_NOT_READY = 44
    ID_ERROR_ACQ_STATE_IS_ALREADY_ACTIVE = 45
    ID_ERROR_ACQ_START_FAILED = 46
    ID_ERROR_ACQ_IS_ACTIVE_CANT_CLOSE_PRG = 47
    ID_ERROR_CANT_START_ACQ_ANALYSIS_EXISTS = 48
    ID_ERROR_CANT_CREATE_ANALYSIS_PATH = 49

    ID_ERROR_REMOTE_INTERACE_NOT_INITIALIZED = 50
    ID_ERROR_REMOTE_INTERACE_IS_ALREADY_IN_USE = 51
    ID_ERROR_REMOTE_DCOM_INTERACE_USED_BY_HYSTAR = 52
    ID_ERROR_REMOTE_DCOM_INTERACE_USED_BY_HPCHEM = 53
    ID_ERROR_REMOTE_DCOM_HYSTAR_CANT_CONNECT_INTERFACE = 54
    ID_ERROR_REMOTE_DCOM_HPCHEM_LC_INSTR_NO_NOT_VALID = 55
    ID_ERROR_REMOTE_DCOM_CANT_USE_CORBA_IS_ACTIVE = 56
    ID_ERROR_REMOTE_CORBA_CANT_USE_DCOM_IS_ACTIVE = 57
    ID_ERROR_REMOTE_CORBA_COMPASS_SERVER_CANT_CONNECT = 58
    ID_ERROR_REMOTE_CORBA_COMPASS_SERVER_CANT_DISCONNECT = 59
    ID_ERROR_COMPASS_SERVER_SAMPLE_INFO_NOT_REQUETED = 60
    ID_ERROR_COMPASS_SERVER_SAMPLE_INFO_NO_METHOD_INFO = 61
    ID_ERROR_COMPASS_SERVER_ACQ_START_NOT_REQUETED = 62
    ID_ERROR_COMPASS_SERVER_CANT_ACTIVATE_REPORTING = 63

    ID_ERROR_PROCESS_QUEUER_CANT_CONNECT = 70
    ID_ERROR_PROCESS_QUEUER_INTERFACE_NOT_AVAILABLE = 71
    ID_ERROR_PROCESS_QUEUER_IS_BUSY = 72

    ID_ERROR_BUSY = 80
    ID_ERROR_ERROR = 81
    ID_ERROR_NO_VARIABLE_LIST = 82
    ID_ERROR_INVALID_VARIABLE_IDX = 83
    ID_ERROR_INVALID_ARGUMENT = 84
    ID_ERROR_SW_NOT_CONNECTED = 85
    ID_ERROR_MS_NOT_CONNECTED = 86
    ID_ERROR_HD_FULL = 87
    ID_ERROR_CFG_FILE_IMCOMPATIBLE_TO_DEVICE_ID = 88
    ID_ERROR_TIMEOUT = 89
    ID_ERROR_CANT_INSERT_SEGMENT = 90
    ID_ERROR_NOT_ENOUGH_MEMORY_FREE = 91
    ID_ERROR_DIGITIZER_INIT_FAILED = 92
    ID_ERROR_ERROR_DIR_WATCH_EMPTY_DIR = 93
    ID_ERROR_ERROR_DIR_WATCH_START_FAILED = 94

    ID_ERROR_METHOD_NO_DIRECTORY = 100
    ID_ERROR_METHOD_NO_NAME = 101
    ID_ERROR_METHOD_NO_TYPE = 102
    ID_ERROR_METHOD_NO_SUBMETHOD_ENTRY_FOR_TYPE = 103
    ID_ERROR_METHOD_IS_READ_ONLY = 104
    ID_ERROR_METHOD_IS_SOP = 105
    ID_ERROR_METHOD_READ_ONLY_CANT_OVERWRITE = 106
    ID_ERROR_METHOD_SOP_CANT_OVERWRITE = 107
    ID_ERROR_METHOD_DESTINATION_ALREADY_EXISTS = 108
    ID_ERROR_METHOD_DESTINATION_NOT_WRITABLE = 109
    ID_ERROR_METHOD_COPY_FAILURE = 110
    ID_ERROR_METHOD_MISSING_RIGHT_MARK_SOP = 111
    ID_ERROR_METHOD_CANT_LOAD = 112
    ID_ERROR_METHOD_CANT_SAVE = 113
    ID_ERROR_METHOD_CANT_GET_SEGMENT = 114
    ID_ERROR_METHOD_NO_CURRENT_SOURCE = 115
    ID_ERROR_METHOD_CANT_FIND_MSMS_SEG = 116
    ID_ERROR_METHOD_CANT_GET_RETENTION_TIME_MASS_LIST = 117
    ID_ERROR_METHOD_CONTENT_IS_INVALID = 118
    ID_ERROR_METHOD_VERSION = 119

    ID_ERROR_DATA_FILE_PATH_IS_EMPTY = 120
    ID_ERROR_DATA_FILE_PATH_SIZE = 121
    ID_ERROR_DATA_FILE_LOAD = 122
    ID_ERROR_DATA_FILE_SAVE = 123

    ID_ERROR_METHODSUB_SAVE_RETENTION_TIME_MASS_LIST = 126
    ID_ERROR_METHODSUB_RTML_EXCEPTION = 127
    ID_ERROR_METHOD_CONVERT = 128

    ID_ERROR_MODE_ACTIVE_CALIBRATE = 130
    ID_ERROR_MODE_ACTIVE_OPTIMIZE = 131
    ID_ERROR_MODE_ACTIVE_ETD_REAGENT = 132

    ID_ERROR_TOF_CALIBRATE_INVALID_PARAMETER = 150
    ID_ERROR_TOF_CALIBRATE_NO_PROCESSING_HISTORY = 151
    ID_ERROR_TOF_CALIBRATE_WRONG_CALIBRATOR_TYPE = 152
    ID_ERROR_TOF_CALIBRATE_NO_PROCESSING_RESULT = 153

    ID_ERROR_QUAD_CALIBRATE_BORDER_TOO_HIGH = 160
    ID_ERROR_QUAD_CALIBRATE_WRONG_NUMBER_OF_PEAKS = 161
    ID_ERROR_QUAD_CALIBRATE_INTENSITY_TOO_LOW = 162
    ID_ERROR_QUAD_CALIBRATE_RESULT_REJECTED_BY_FIRMWARE = 163
    ID_ERROR_QUAD_CALIBRATE_WRONG_NUMBER_OF_PEAKS_FC = 164
    ID_ERROR_QUAD_CALIBRATE_BACKUP_FAILED = 165
    ID_ERROR_QUAD_CALIBRATE_NO_CALIBRANTS = 166
    ID_ERROR_QUAD_CALIBRATE_TO_MUCH_TASK_IDS = 167

    ID_ERROR_PARA_NULLPOINTER_FOR_VALID_INDEX = 170
    ID_ERROR_PARA_NULLPOINTER = 171

    ID_ERROR_MERGE_FILE_LOAD = 180
    ID_ERROR_MERGE_FILE_SAVE = 181
    ID_ERROR_MERGE_FILE_EMPTY = 182
    ID_ERROR_MERGE_TYPE_NOT_AVAILABLE = 183
    ID_ERROR_MERGE_INVALID_OPTION = 184

    ID_ERROR_AUTOTUNE_WRONG_NUMBER_OF_RAMP_POINTS = 190
    ID_ERROR_AUTOTUNE_DIGOFFS_SEARCHVALUE_NOTFOUND = 191
    ID_ERROR_AUTOTUNE_DIGNOISE_SEARCHVALUE_NOTFOUND = 192
    ID_ERROR_AUTOTUNE_CHECK_INTENSITY_TOO_LOW = 193
    ID_ERROR_AUTOTUNE_DETECTORTOF_SEARCHVALUE_NOTFOUND = 194
    ID_ERROR_AUTOTUNE_DETECTOR_WITHOUT_CAPEXIT = 195
    ID_ERROR_AUTOTUNE_MSMS_MRM_SEARCHVALUE_NOTFOUND = 196
    ID_ERROR_AUTOTUNE_GA_IN_ERROR = 197
    ID_ERROR_AUTOTUNETOF_DLL_NOTFOUND = 198
    ID_ERROR_AUTOTUNEALG_DLL_NOTFOUND = 199

    ID_ERROR_HVC_SWITCH_TYPE_UNSUPPORTED = 200

    ID_ERROR_CSV_FILE_IMPORT_INVALID_NAME = 210
    ID_ERROR_CSV_FILE_IMPORT_INVALID_NUMBER_OF_COLUMNS = 211
    ID_ERROR_CSV_FILE_IMPORT_NO_ENTRIES = 212
    ID_ERROR_CSV_FILE_IMPORT_TOO_MUCH_ENTRIES = 213

    ID_ERROR_METHODPART_CANT_FIND_MSMS_SEG = 220
    ID_ERROR_METHODPART_NO_VALID_PARTPARAMETERS = 221
    ID_ERROR_METHODPART_SOME_INVALID_PARTPARAMETERS = 222

    ID_ERROR_METHOD_REPORT_CANT_CANCEL = 230
    ID_ERROR_METHOD_REPORT_CANT_CREATE = 231
    ID_ERROR_METHOD_REPORT_REPORT_IS_EMPTY = 232

    @classmethod
    def check_return(cls, val):
        val = cls(val)
        if val != cls.ID_ERROR_NO_ERROR:
            raise BrukerMSError(val)
